Import('*')

env.Append(LIBS = ['SDL', 'm'])
env.Append(CFLAGS = ['-Wall', '-O3', '-fomit-frame-pointer', '-funroll-loops'])
#env.Append(CFLAGS = ['-Wall', '-g3'])

if target == 'win32':
    env.Append(LIBS = ['opengl32', 'glu32', 'gdi32'])
else:
    env.Append(LIBS = ['GL', 'GLU', 'X11'])

env.Program('../atest', Glob('*.c'))
